<template>
<div>
    <div v-if="loading" style="text-align:center; margin-top:15rem;">
        <div class="loadingio-spinner-ellipsis-f9g8sm63oof"><div class="ldio-mr6hs88yhu">
        <div></div><div></div><div></div><div></div><div></div>
        </div></div>
    </div>
    <div style="width:100%" v-else>
        <h5 style="font-size:calc(125% + 1vw); width:100%; text-align:center;" >Berita Informatika</h5>
        <ul style="display: grid; grid-template-columns:repeat(auto-fit, minmax(400px,1fr)); padding:0;">
            <li v-for="item in listBerita" :key="item._id" style="display:inline; padding: 10px; ">
                <div class="shadow p-0 mb-3 bg-white rounded">
                    <div class="card-body">
                        <p style=" font-size:calc(80% + 0.5vw);font-weight:bold;">{{item.judul_berita}}</p>
                    <div v-html="item.isi_berita"></div>
                    <div v-if="item.file != null">
                        <span><a :href="item.file" target="_blank" :download="item.judul_berita">Download File Disini!</a></span>
                    </div>
                    </div>
                    <div class="card-footer text-muted">
                        {{item.tanggal}}
                    </div>
                </div>
                
            </li>
        </ul>
    </div>
</div>
    
</template>

<script>

import axios from 'axios'

//import moment from 'moment';

export default {
    name: 'ListBerita',
    compatConfig: { MODE: 3 },
    data(){
        return {
            text: 'Pengumuman',
            firebaseUID: null,
            dataDiri: [],
            listBerita: [],
            loading:true,
        }
    },
    created() {
        if(sessionStorage.getItem('firebase-token') && sessionStorage.getItem('firebase-uid')){
            this.getProfile()
        }
    },
    methods:{
        async getBerita(){
            await axios.get(`https://beritaapi.fti.ukdw.ac.id/news`).then((response)=>{
                this.listBerita = response.data
                this.loading = false
            })
        },
        async getProfile() {
            this.firebaseUID = JSON.parse(sessionStorage.getItem('firebase-uid'))
            await axios.get(`https://userapi.fti.ukdw.ac.id/${this.firebaseUID.uid}`)
            .then((response) => {
                this.dataDiri = response.data
                this.getBerita()
            })
        },
    }

}
</script>
<style scoped>
@keyframes ldio-mr6hs88yhu {
   0% { transform: translate(12px,80px) scale(0); }
  25% { transform: translate(12px,80px) scale(0); }
  50% { transform: translate(12px,80px) scale(1); }
  75% { transform: translate(80px,80px) scale(1); }
 100% { transform: translate(148px,80px) scale(1); }
}
@keyframes ldio-mr6hs88yhu-r {
   0% { transform: translate(148px,80px) scale(1); }
 100% { transform: translate(148px,80px) scale(0); }
}
@keyframes ldio-mr6hs88yhu-c {
   0% { background: #93dbe9 }
  25% { background: #3b4368 }
  50% { background: #5e6fa3 }
  75% { background: #689cc5 }
 100% { background: #93dbe9 }
}
.ldio-mr6hs88yhu div {
  position: absolute;
  width: 40px;
  height: 40px;
  border-radius: 50%;
  transform: translate(80px,80px) scale(1);
  background: #93dbe9;
  animation: ldio-mr6hs88yhu 1s infinite cubic-bezier(0,0.5,0.5,1);
}
.ldio-mr6hs88yhu div:nth-child(1) {
  background: #689cc5;
  transform: translate(148px,80px) scale(1);
  animation: ldio-mr6hs88yhu-r 0.25s infinite cubic-bezier(0,0.5,0.5,1), ldio-mr6hs88yhu-c 1s infinite step-start;
}.ldio-mr6hs88yhu div:nth-child(2) {
  animation-delay: -0.25s;
  background: #93dbe9;
}.ldio-mr6hs88yhu div:nth-child(3) {
  animation-delay: -0.5s;
  background: #689cc5;
}.ldio-mr6hs88yhu div:nth-child(4) {
  animation-delay: -0.75s;
  background: #5e6fa3;
}.ldio-mr6hs88yhu div:nth-child(5) {
  animation-delay: -1s;
  background: #3b4368;
}
.loadingio-spinner-ellipsis-f9g8sm63oof {
  width: 200px;
  height: 200px;
  display: inline-block;
  overflow: hidden;
  background: transparent;
}
.ldio-mr6hs88yhu {
  width: 100%;
  height: 100%;
  position: relative;
  transform: translateZ(0) scale(1);
  backface-visibility: hidden;
  transform-origin: 0 0; /* see note above */
}
.ldio-mr6hs88yhu div { box-sizing: content-box; }
/* generated by https://loading.io/ */
</style>